version: 2

staging:
  - name: stg_cc_parcel
    columns:
      ### PK ###
      - name: parcel_id
        tests:
          - unique
          - not_null
  - name: stg_cc_parcel_product
    columns:
      ### PK ###
      - name: parcel_id
        tests:
          - unique
          - not_null
          